/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesIHM;

import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;

import LesClasses.Constellation;
import LesClasses.LeJeu;

/**
 *
 * @author luc.bournel
 */
public class FenetreAffichageConstellation extends javax.swing.JFrame {

    /**
     * Creates new form FenetreAffichageConstellation
     *
     * @param uneConstellation
     */
    public FenetreAffichageConstellation(Constellation uneConstellation) {
        initComponents();
        setComponents(uneConstellation);
        Timer timerFPS = new Timer();
        timerFPS.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                LeJeu.afficherFPS(FenetreAffichageConstellation.this, "la piste aux étoiles");
            }
        }, 0, 1);
    }

    private void setComponents(Constellation maConstel) {
        //setBackground(new Color(0f, 0f, 0.41f));
        labNomConstellation.setText(maConstel.getleNom());
        Icon img = new ImageIcon(maConstel.getlImage());
        labImage.setIcon(img);
        LabEtoile1.setText(maConstel.getLaListeEtoiles().get(0).getAppellation());
        LabEtoile2.setText(maConstel.getLaListeEtoiles().get(1).getAppellation());
        LabEtoile3.setText(maConstel.getLaListeEtoiles().get(2).getAppellation());
        LabEtoile4.setText(maConstel.getLaListeEtoiles().get(3).getAppellation());

        jPanel2.setBackground(LeJeu.getPrimaryColor());
        jPanel3.setBackground(LeJeu.getPrimaryColor());
        jPanel4.setBackground(LeJeu.getPrimaryColor());
        jPanel5.setBackground(LeJeu.getPrimaryColor());
        jPanel6.setBackground(LeJeu.getPrimaryColor());

        setBackground(LeJeu.getSecondaryColor());
        jPanel1.setBackground(LeJeu.getSecondaryColor());
        panneauBasFenetre.setBackground(LeJeu.getSecondaryColor());
        panneauLesLabels.setBackground(LeJeu.getSecondaryColor());

        LabEtoile1.setForeground(LeJeu.getTextColor());
        LabEtoile2.setForeground(LeJeu.getTextColor());
        LabEtoile3.setForeground(LeJeu.getTextColor());
        LabEtoile4.setForeground(LeJeu.getTextColor());
        labNomConstellation.setForeground(LeJeu.getTextColor());
        leTexte.setForeground(LeJeu.getTextColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labNomConstellation = new javax.swing.JLabel();
        labImage = new javax.swing.JLabel();
        panneauBasFenetre = new java.awt.Panel();
        jPanel3 = new javax.swing.JPanel();
        leTexte = new javax.swing.JLabel();
        panneauLesLabels = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        LabEtoile1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        LabEtoile2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        LabEtoile3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        LabEtoile4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("la piste aux étoiles");
        setBackground(new java.awt.Color(0, 1, 104));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        setLocation(new java.awt.Point(448, 156));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 1, 104));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new java.awt.BorderLayout());

        labNomConstellation.setBackground(new java.awt.Color(0, 1, 104));
        labNomConstellation.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        labNomConstellation.setForeground(new java.awt.Color(255, 255, 255));
        labNomConstellation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNomConstellation.setText("jLabel1");
        jPanel1.add(labNomConstellation, java.awt.BorderLayout.PAGE_START);

        labImage.setBackground(new java.awt.Color(0, 1, 104));
        labImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labImage, java.awt.BorderLayout.CENTER);

        panneauBasFenetre.setBackground(new java.awt.Color(0, 1, 104));
        panneauBasFenetre.setMinimumSize(new java.awt.Dimension(300, 159));
        panneauBasFenetre.setPreferredSize(new java.awt.Dimension(1024, 200));
        panneauBasFenetre.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jPanel3.setBackground(new java.awt.Color(57, 0, 101));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new java.awt.BorderLayout());

        leTexte.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        leTexte.setForeground(new java.awt.Color(255, 255, 255));
        leTexte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leTexte.setText("Les étoiles à mémoriser sont :");
        jPanel3.add(leTexte, java.awt.BorderLayout.CENTER);

        panneauBasFenetre.add(jPanel3);

        panneauLesLabels.setBackground(new java.awt.Color(0, 1, 104));
        panneauLesLabels.setPreferredSize(new java.awt.Dimension(500, 50));
        panneauLesLabels.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jPanel2.setBackground(new java.awt.Color(57, 0, 101));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new java.awt.BorderLayout());

        LabEtoile1.setBackground(new java.awt.Color(255, 0, 0));
        LabEtoile1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabEtoile1.setForeground(new java.awt.Color(255, 255, 255));
        LabEtoile1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabEtoile1.setText("jLabel1");
        jPanel2.add(LabEtoile1, java.awt.BorderLayout.CENTER);

        panneauLesLabels.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(57, 0, 101));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new java.awt.BorderLayout());

        LabEtoile2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabEtoile2.setForeground(new java.awt.Color(255, 255, 255));
        LabEtoile2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabEtoile2.setText("jLabel2");
        jPanel4.add(LabEtoile2, java.awt.BorderLayout.CENTER);

        panneauLesLabels.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(57, 0, 101));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new java.awt.BorderLayout());

        LabEtoile3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabEtoile3.setForeground(new java.awt.Color(255, 255, 255));
        LabEtoile3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabEtoile3.setText("jLabel3");
        jPanel5.add(LabEtoile3, java.awt.BorderLayout.CENTER);

        panneauLesLabels.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(57, 0, 101));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new java.awt.BorderLayout());

        LabEtoile4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        LabEtoile4.setForeground(new java.awt.Color(255, 255, 255));
        LabEtoile4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabEtoile4.setText("jLabel4");
        jPanel6.add(LabEtoile4, java.awt.BorderLayout.CENTER);

        panneauLesLabels.add(jPanel6);

        panneauBasFenetre.add(panneauLesLabels);

        jPanel1.add(panneauBasFenetre, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabEtoile1;
    private javax.swing.JLabel LabEtoile2;
    private javax.swing.JLabel LabEtoile3;
    private javax.swing.JLabel LabEtoile4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labImage;
    private javax.swing.JLabel labNomConstellation;
    private javax.swing.JLabel leTexte;
    private java.awt.Panel panneauBasFenetre;
    private java.awt.Panel panneauLesLabels;
    // End of variables declaration//GEN-END:variables
}
