package lesIHM;

import java.awt.Container;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

/**
 *
 * @author luc.bournel
 */
public class FenetreInterface extends javax.swing.JFrame {

    /**
     * Creates new form RecapFenetreInterface
     */
    public FenetreInterface() {
        initComponents();
        ajoutImage();
    }

    private void ajoutImage() {
        // Code à ajouter ici pour afficher l'image de la constellation du Gemeaux
        Icon img = new ImageIcon("gemeaux.gif");
        lImage.setIcon(img);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        leTexte = new javax.swing.JLabel();
        panneauBoutons = new javax.swing.JPanel();
        btnAfficheMessage1 = new javax.swing.JButton();
        btnAfficheMessage2 = new javax.swing.JButton();
        btnCreationFenetre = new javax.swing.JButton();
        btnFermetureFenetre = new javax.swing.JButton();
        lImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pour apprendre à gérer les évènements");
        setPreferredSize(new java.awt.Dimension(800, 800));

        leTexte.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        leTexte.setText("Cliquer sur les différents boutons puis consulter le code associé.");
        leTexte.setPreferredSize(new java.awt.Dimension(348, 30));
        getContentPane().add(leTexte, java.awt.BorderLayout.NORTH);

        panneauBoutons.setPreferredSize(new java.awt.Dimension(100, 100));
        panneauBoutons.setLayout(new java.awt.GridLayout(2, 2));

        btnAfficheMessage1.setText("Affichage message 1");
        btnAfficheMessage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficheMessage1ActionPerformed(evt);
            }
        });
        panneauBoutons.add(btnAfficheMessage1);

        btnAfficheMessage2.setText("Affichage message 2");
        btnAfficheMessage2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfficheMessage2ActionPerformed(evt);
            }
        });
        panneauBoutons.add(btnAfficheMessage2);

        btnCreationFenetre.setText("Créer une nouvelle fenêtre");
        btnCreationFenetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreationFenetreActionPerformed(evt);
            }
        });
        panneauBoutons.add(btnCreationFenetre);

        btnFermetureFenetre.setText("Fermer la fenêtre");
        btnFermetureFenetre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFermetureFenetreActionPerformed(evt);
            }
        });
        panneauBoutons.add(btnFermetureFenetre);

        getContentPane().add(panneauBoutons, java.awt.BorderLayout.CENTER);

        lImage.setText("jLabel1");
        lImage.setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().add(lImage, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>                        

    private void btnAfficheMessage1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }

    private void btnAfficheMessage2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }

    private void btnCreationFenetreActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }

    private void btnFermetureFenetreActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }

    private void maGestionDeLEvenement(java.awt.event.ActionEvent evt) {
        Object source = evt.getSource();

        if (source == btnAfficheMessage1) {
            JOptionPane.showMessageDialog(null, "clic sur le bouton message 1");
        } else if (source == btnAfficheMessage2) {
            JOptionPane.showMessageDialog(null, "clic sur le bouton message 2");
        } else if (source == btnFermetureFenetre) {
            System.exit(DISPOSE_ON_CLOSE);
        } else if (source == btnCreationFenetre) {
            Thread nouveauFilExecution;
            nouveauFilExecution = new Thread(new Runnable() {
                public void run() {
                    JFrame laNvFenetre;
                    try {
                        laNvFenetre = new JFrame();
                        laNvFenetre.setSize(300, 300);
                        laNvFenetre.setTitle("Nouvelle fenetre");
                        Container panneauNvFenetre = laNvFenetre.getContentPane();
                        panneauNvFenetre.add(new JLabel("Attendre la fermeture!!"));
                        laNvFenetre.setVisible(true);
                        Thread.sleep(1000);
                        laNvFenetre.dispose();
                    } catch (Exception e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                }
            }
            );
            nouveauFilExecution.start();
        }

    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAfficheMessage1;
    private javax.swing.JButton btnAfficheMessage2;
    private javax.swing.JButton btnCreationFenetre;
    private javax.swing.JButton btnFermetureFenetre;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel leTexte;
    private javax.swing.JPanel panneauBoutons;
    // End of variables declaration                   
}
