/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesIHM;

import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JSlider;

import lesClasses.LeJeu;

/**
 *
 * @author luc.bournel
 */
public class FenetreOptions extends javax.swing.JFrame {

    /**
     * Creates new form FenetreOptions
     */
    public FenetreOptions() {
        initComponents();
        checkboxFPS.setSelected(LeJeu.isShowFPS());
        sliderSecondes.setValue(LeJeu.getSeconds());
        setComponents();
        Timer timerFPS = new Timer();
        timerFPS.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                LeJeu.afficherFPS(FenetreOptions.this, "Le Jeu Sérieux");
            }
        }, 0, 1);
    }
    
    private void setComponents() {
        boutonQuitter.setBackground(LeJeu.getPrimaryColor());
        buttonForegroundColor.setBackground(LeJeu.getPrimaryColor());
        
        setBackground(LeJeu.getSecondaryColor());
        jPanel1.setBackground(LeJeu.getSecondaryColor());
        jPanel2.setBackground(LeJeu.getSecondaryColor());
        buttonBackgroundColor.setBackground(LeJeu.getSecondaryColor());
        
        jLabel1.setForeground(LeJeu.getTextColor());
        jLabel2.setForeground(LeJeu.getTextColor());
        jLabel3.setForeground(LeJeu.getTextColor());
        jLabel4.setForeground(LeJeu.getTextColor());
        jLabel5.setForeground(LeJeu.getTextColor());
        boutonQuitter.setForeground(LeJeu.getTextColor());
        secondesText.setForeground(LeJeu.getTextColor());
        labNomConstellation.setForeground(LeJeu.getTextColor());
        buttonBackgroundColor.setForeground(LeJeu.getTextColor());
        buttonForegroundColor.setForeground(LeJeu.getTextColor());
        buttonTextColor.setBackground(LeJeu.getTextColor());
        buttonTextColor.setForeground(LeJeu.getPrimaryColor());
    }
    
    private Color showColorWindow(Color color) {
        /*jColorChooser1.setVisible(true);
        jColorChooser1.setColor(color);*/
        return JColorChooser.showDialog(this, "Choose Color", color);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        boutonQuitter = new javax.swing.JButton();
        labNomConstellation = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        checkboxFPS = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        sliderSecondes = new javax.swing.JSlider();
        secondesText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonForegroundColor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        buttonBackgroundColor = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        buttonTextColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Le Jeu Sérieux");
        setBackground(new java.awt.Color(0, 1, 107));
        setLocation(new java.awt.Point(448, 156));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 1, 107));
        jPanel1.setLayout(new java.awt.BorderLayout());

        boutonQuitter.setBackground(new java.awt.Color(57, 0, 101));
        boutonQuitter.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        boutonQuitter.setForeground(new java.awt.Color(255, 255, 255));
        boutonQuitter.setText("Quitter");
        boutonQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonQuitterActionPerformed(evt);
            }
        });
        jPanel1.add(boutonQuitter, java.awt.BorderLayout.SOUTH);

        labNomConstellation.setBackground(new java.awt.Color(0, 1, 104));
        labNomConstellation.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        labNomConstellation.setForeground(new java.awt.Color(255, 255, 255));
        labNomConstellation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNomConstellation.setText("Options");
        jPanel1.add(labNomConstellation, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(0, 1, 107));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {2};
        jPanel2.setLayout(jPanel2Layout);

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Voir IPS :");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        checkboxFPS.setBackground(new java.awt.Color(0, 1, 107));
        checkboxFPS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxFPSActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel2.add(checkboxFPS, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Temps réflexion :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jLabel2, gridBagConstraints);

        sliderSecondes.setMaximum(30);
        sliderSecondes.setMinimum(5);
        sliderSecondes.setValue(10);
        sliderSecondes.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderSecondesStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(sliderSecondes, gridBagConstraints);

        secondesText.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        secondesText.setForeground(new java.awt.Color(255, 255, 255));
        secondesText.setText("10 s");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(secondesText, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Couleur Principale :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel3, gridBagConstraints);

        buttonForegroundColor.setText("Choisir Couleur");
        buttonForegroundColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonForegroundColorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel2.add(buttonForegroundColor, gridBagConstraints);

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Couleur Secondaire :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(jLabel4, gridBagConstraints);

        buttonBackgroundColor.setText("Choisir Couleur");
        buttonBackgroundColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackgroundColorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(buttonBackgroundColor, gridBagConstraints);

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Couleur Texte :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel5, gridBagConstraints);

        buttonTextColor.setText("Choisir Couleur");
        buttonTextColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTextColorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel2.add(buttonTextColor, gridBagConstraints);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxFPSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxFPSActionPerformed
        JCheckBox source = (JCheckBox) evt.getSource();
        LeJeu.setShowFPS(source.isSelected());
    }//GEN-LAST:event_checkboxFPSActionPerformed

    private void boutonQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonQuitterActionPerformed
        LeJeu.setSeconds(sliderSecondes.getValue());
        this.dispose();
    }//GEN-LAST:event_boutonQuitterActionPerformed

    private void sliderSecondesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderSecondesStateChanged
        JSlider slider = (JSlider) evt.getSource();
        secondesText.setText((slider.getValue() < 10 ? "0" : "") + slider.getValue() + "s");
    }//GEN-LAST:event_sliderSecondesStateChanged

    private void buttonForegroundColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonForegroundColorActionPerformed
        LeJeu.setPrimaryColor(showColorWindow(LeJeu.getPrimaryColor()));
        setComponents();
    }//GEN-LAST:event_buttonForegroundColorActionPerformed

    private void buttonBackgroundColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackgroundColorActionPerformed
        LeJeu.setSecondaryColor(showColorWindow(LeJeu.getSecondaryColor()));
        setComponents();
    }//GEN-LAST:event_buttonBackgroundColorActionPerformed

    private void buttonTextColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTextColorActionPerformed
        LeJeu.setTextColor(showColorWindow(LeJeu.getTextColor()));
        setComponents();
    }//GEN-LAST:event_buttonTextColorActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boutonQuitter;
    private javax.swing.JButton buttonBackgroundColor;
    private javax.swing.JButton buttonForegroundColor;
    private javax.swing.JButton buttonTextColor;
    private javax.swing.JCheckBox checkboxFPS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labNomConstellation;
    private javax.swing.JLabel secondesText;
    private javax.swing.JSlider sliderSecondes;
    // End of variables declaration//GEN-END:variables
}
