/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lesIHM;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

import LesClasses.Constellation;
import LesClasses.LeJeu;

import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author luc.bournel
 */
public class FenetreJeuConstellation extends javax.swing.JFrame {

    private boolean continuer = false;
    private String lIntrus;
    private Timer timer, timerFPS;
    private int secondes, millisecondes;

    /* Add score system
    private static int score = 0;
    private void AddPoint() { score++ ;}
    private void resetScore() { score = 0; }
    */

    /**
     * Creates new form FenetreJeuConstellation
     *
     * @param laConstellation
     */
    public FenetreJeuConstellation(Constellation laConstellation) {
        initComponents();
        lIntrus = laConstellation.getlaMauvaiseRep().getAppellation();
        setComponent(laConstellation);
        secondes = LeJeu.getSeconds();
        millisecondes = 00;
        timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                millisecondes--;
                if (millisecondes < 0) {
                    millisecondes = 100;
                    secondes--;
                }
                labelTimer.setText((secondes < 10 ? "0" : "") + secondes + ":" + (millisecondes < 10 ? "0" : "") + millisecondes);
            }
        }, 0, 10);

        timerFPS = new Timer();
        timerFPS.scheduleAtFixedRate(new TimerTask() {

            @Override
            public void run() {
                LeJeu.afficherFPS(FenetreJeuConstellation.this, "la piste aux étoiles");
            }
        }, 0, 1);
    }

    private void setComponent(Constellation maConstel) {
        labNomConstellation.setText(maConstel.getleNom());
        Icon img = new ImageIcon(/*"SE" + */maConstel.getlImage()); // rajouter SE pour afficher les constallation avec me nom des étoiles
        labImage.setIcon(img);
        jButton1.setText(maConstel.getLaListeEtoiles().get(0).getAppellation());
        jButton2.setText(maConstel.getLaListeEtoiles().get(1).getAppellation());
        jButton3.setText(maConstel.getLaListeEtoiles().get(2).getAppellation());
        jButton4.setText(maConstel.getLaListeEtoiles().get(3).getAppellation());

        jButton1.setBackground(LeJeu.getPrimaryColor());
        jButton2.setBackground(LeJeu.getPrimaryColor());
        jButton3.setBackground(LeJeu.getPrimaryColor());
        jButton4.setBackground(LeJeu.getPrimaryColor());
        jPanel2.setBackground(LeJeu.getPrimaryColor());
        jPanel3.setBackground(LeJeu.getPrimaryColor());
        jPanel4.setBackground(LeJeu.getPrimaryColor());
        jPanel5.setBackground(LeJeu.getPrimaryColor());
        jPanel6.setBackground(LeJeu.getPrimaryColor());

        setBackground(LeJeu.getSecondaryColor());
        jPanel1.setBackground(LeJeu.getSecondaryColor());
        jPanel7.setBackground(LeJeu.getSecondaryColor());
        panneauBasFenetre.setBackground(LeJeu.getSecondaryColor());
        panneauLesLabels.setBackground(LeJeu.getSecondaryColor());

        jLabel1.setForeground(LeJeu.getTextColor());
        jButton1.setForeground(LeJeu.getTextColor());
        jButton2.setForeground(LeJeu.getTextColor());
        jButton3.setForeground(LeJeu.getTextColor());
        jButton4.setForeground(LeJeu.getTextColor());
        labNomConstellation.setForeground(LeJeu.getTextColor());
        labelTimer.setForeground(LeJeu.getTextColor());
        leTexte.setForeground(LeJeu.getTextColor());
    }

    private void bloqueBoutons() {
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
    }

    private void maGestionDeLEvenement(java.awt.event.ActionEvent evt) {
        JButton source = (JButton) evt.getSource();

        bloqueBoutons();

        if (source.getText().equals(lIntrus)) {
            JOptionPane.showMessageDialog(null, "Bravo !");
            continuer = true;
            /* if(score == 6) {
                // Afficher vue enregistrement
            }*/
        } else {
            JOptionPane.showMessageDialog(null, "Perdu !");
            // resetScore();
        }

    }

    public boolean getContinuer() {
        return continuer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        labelTimer = new javax.swing.JLabel();
        labNomConstellation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labImage = new javax.swing.JLabel();
        panneauBasFenetre = new java.awt.Panel();
        jPanel3 = new javax.swing.JPanel();
        leTexte = new javax.swing.JLabel();
        panneauLesLabels = new java.awt.Panel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("la piste aux étoiles");
        setLocation(new java.awt.Point(448, 156));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 1, 104));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 768));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(0, 1, 107));
        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        labelTimer.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        labelTimer.setForeground(new java.awt.Color(255, 255, 255));
        labelTimer.setText("10:00");
        labelTimer.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labelTimer.setPreferredSize(new java.awt.Dimension(20, 44));
        labelTimer.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel7.add(labelTimer);

        labNomConstellation.setBackground(new java.awt.Color(0, 1, 104));
        labNomConstellation.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        labNomConstellation.setForeground(new java.awt.Color(255, 255, 255));
        labNomConstellation.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labNomConstellation.setText("jLabel1");
        jPanel7.add(labNomConstellation);
        jPanel7.add(jLabel1);

        jPanel1.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        labImage.setBackground(new java.awt.Color(0, 1, 104));
        labImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(labImage, java.awt.BorderLayout.CENTER);

        panneauBasFenetre.setBackground(new java.awt.Color(0, 1, 104));
        panneauBasFenetre.setLayout(new java.awt.GridLayout(2, 1, 0, 5));

        jPanel3.setBackground(new java.awt.Color(57, 0, 101));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel3.setLayout(new java.awt.BorderLayout());

        leTexte.setFont(new java.awt.Font("Calibri", 0, 36)); // NOI18N
        leTexte.setForeground(new java.awt.Color(255, 255, 255));
        leTexte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leTexte.setText("Quel est l'intrus ?");
        jPanel3.add(leTexte, java.awt.BorderLayout.CENTER);

        panneauBasFenetre.add(jPanel3);

        panneauLesLabels.setBackground(new java.awt.Color(0, 1, 104));
        panneauLesLabels.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jPanel2.setBackground(new java.awt.Color(57, 0, 101));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(57, 0, 101));
        jButton1.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, java.awt.BorderLayout.PAGE_START);

        panneauLesLabels.add(jPanel2);

        jPanel4.setBackground(new java.awt.Color(57, 0, 101));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton2.setBackground(new java.awt.Color(57, 0, 101));
        jButton2.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("jButton1");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, java.awt.BorderLayout.PAGE_START);

        panneauLesLabels.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(57, 0, 101));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setBackground(new java.awt.Color(57, 0, 101));
        jButton3.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, java.awt.BorderLayout.PAGE_START);

        panneauLesLabels.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(57, 0, 101));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(0));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton4.setBackground(new java.awt.Color(57, 0, 101));
        jButton4.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton4, java.awt.BorderLayout.PAGE_START);

        panneauLesLabels.add(jPanel6);

        panneauBasFenetre.add(panneauLesLabels);

        jPanel1.add(panneauBasFenetre, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        maGestionDeLEvenement(evt);
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labImage;
    private javax.swing.JLabel labNomConstellation;
    private javax.swing.JLabel labelTimer;
    private javax.swing.JLabel leTexte;
    private java.awt.Panel panneauBasFenetre;
    private java.awt.Panel panneauLesLabels;
    // End of variables declaration//GEN-END:variables
}
