package lesIHM;

import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;

import LesClasses.LeJeu;

/**
 *
 * @author Armelle MUNDUBELTZ
 */
public class FenetreLancement extends javax.swing.JFrame {

    private boolean premiereFois = true;

    /**
     * Creates new form JFrameLancement
     */
    public FenetreLancement() {

        try {
            LeJeu.charger();
            initComponents();
            Timer timerFPS = new Timer();
            timerFPS.scheduleAtFixedRate(new TimerTask() {
                @Override
                public void run() {
                    LeJeu.afficherFPS(FenetreLancement.this, "Le Jeu Sérieux");
                    setComponents();
                }
            }, 0, 1);
        } catch (Exception ex) {
            Logger.getLogger(FenetreLancement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void setComponents() {
        btnApprentissage.setBackground(LeJeu.getPrimaryColor());
        btnJeu.setBackground(LeJeu.getPrimaryColor());
        buttonOptions.setBackground(LeJeu.getPrimaryColor());

        setBackground(LeJeu.getSecondaryColor());
        jPanel1.setBackground(LeJeu.getSecondaryColor());
        jPanel2.setBackground(LeJeu.getSecondaryColor());
        jPanel3.setBackground(LeJeu.getSecondaryColor());

        jLabel1.setForeground(LeJeu.getTextColor());
        btnApprentissage.setForeground(LeJeu.getTextColor());
        btnJeu.setForeground(LeJeu.getTextColor());
        buttonOptions.setForeground(LeJeu.getTextColor());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnApprentissage = new javax.swing.JButton();
        btnJeu = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonOptions = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Le Jeu Sérieux");
        setLocation(new java.awt.Point(448, 156));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 1, 107));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(0, 1, 107));
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Le Jeu Sérieux");
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(0, 1, 107));
        jPanel1.setForeground(new java.awt.Color(0, 1, 104));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        btnApprentissage.setBackground(new java.awt.Color(57, 0, 101));
        btnApprentissage.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnApprentissage.setForeground(new java.awt.Color(255, 255, 255));
        btnApprentissage.setText("Lancer la phase d'apprentissage");
        btnApprentissage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApprentissageActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(btnApprentissage, gridBagConstraints);

        btnJeu.setBackground(new java.awt.Color(57, 0, 101));
        btnJeu.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        btnJeu.setForeground(new java.awt.Color(255, 255, 255));
        btnJeu.setText("Lancer la phase de jeu");
        btnJeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJeuActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 75;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 20, 0, 20);
        jPanel1.add(btnJeu, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(0, 1, 107));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        buttonOptions.setBackground(new java.awt.Color(57, 0, 101));
        buttonOptions.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        buttonOptions.setForeground(new java.awt.Color(255, 255, 255));
        buttonOptions.setText("Options");
        buttonOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOptionsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 19, 56, 19);
        jPanel3.add(buttonOptions, gridBagConstraints);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnApprentissageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApprentissageActionPerformed
        maProcedureActionPerformed(evt);
    }//GEN-LAST:event_btnApprentissageActionPerformed

    private void btnJeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJeuActionPerformed
        maProcedureActionPerformed(evt);
    }//GEN-LAST:event_btnJeuActionPerformed

    private void buttonOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOptionsActionPerformed
        maProcedureActionPerformed(evt);
    }//GEN-LAST:event_buttonOptionsActionPerformed

    private void maProcedureActionPerformed(java.awt.event.ActionEvent evt) {
        Object source = evt.getSource();
        if (source == btnApprentissage) {
            btnApprentissage.setEnabled(false);
            threadApprentissage = new Thread(new PlayApprentissage());
            threadApprentissage.start();
        } else if (source == btnJeu) {
            if (premiereFois) {
                LeJeu.affecterMauvaiseReponses();
                premiereFois = false;
            }

            threadJeu = new Thread(new PlayJeu());
            threadJeu.start();
        } else if (source == buttonOptions) {
            lancerOptions();
        }
    }

    private void lancerOptions() {
        Thread nouveauFilExecution = new Thread(new Runnable() {
            public void run() {
                FenetreOptions laNvFenetre;
                try {
                    laNvFenetre = new FenetreOptions();
                    laNvFenetre.setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
        );
        nouveauFilExecution.start();
    }

    private class PlayApprentissage implements Runnable {

        @Override
        public void run() {
            try {
                LeJeu.afficherApprentissage();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private class PlayJeu implements Runnable {

        @Override
        public void run() {
            try {
                LeJeu.afficherJeu();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreLancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreLancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreLancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreLancement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreLancement().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprentissage;
    private javax.swing.JButton btnJeu;
    private javax.swing.JButton buttonOptions;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
    private Thread threadApprentissage;
    private Thread threadJeu;
}
